#pragma once

// Hand-written modules, as cls.cpp : the CPython tables and structs are declared positionally, and
// the PyCFunction casts are the ones the generated code makes.
//
// This can not be generated by clair instead : c2py_a and c2py_b each need their own, independently
// registered PyTypeObject for the *same* C++ type L, to exercise import-order and conflict detection
// in the pto table. Clair's model is one C++ type <-> one generated wrapper, and it would refuse to
// help here even given the chance : by default it only wraps declarations found in the module's own
// .cpp (its match_files defaults to that filename, so L living in this header is invisible to it
// anyway), and were match_files widened to reach this header, it would still reject L because of the
// `is_wrapped<L> = true` below, i.e. exactly the annotation that says "do not generate a wrapper,
// something else already provides one".
#ifdef __clang__
#pragma clang diagnostic ignored "-Wmissing-field-initializers"
#pragma clang diagnostic ignored "-Wcast-function-type-mismatch"
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#pragma GCC diagnostic ignored "-Wcast-function-type"
#endif

#include "c2py/c2py.hpp"

// The C++ type the modules of this directory share. What matters is that they all wrap *the same*
// type : the tables are keyed on the mangled name, so they all compete for one entry.
struct L {
  int k = 0;
};

template <> constexpr bool c2py::is_wrapped<L> = true;
