// Registers a Python type for L the way a module built with the legacy cpp2py does : a holder
// { PyObject_HEAD; L *_c; }, no parent and no is_const field, written into __main__.__cpp2py_table
// by a plain assignment.
//
// The assignment matters : cpp2py does `conv_table[typeid(T).name()] = &its_type;`
// (cpp2py/mako/wrap.cxx), it overwrites whatever is there. Going through c2py's
// register_pto_in_legacy_table instead would keep the first entry and would not model a legacy
// module imported after a c2py one.

#include "L.hpp"

// The layout generated by the legacy cpp2py
struct legacy_holder_t {
  PyObject_HEAD //;
     L *_c;
};

// ... and its dealloc : it knows nothing of a parent, it always owns its L
static void legacy_dealloc(PyObject *self) {
  auto *c_ptr = ((legacy_holder_t *)self)->_c;
  if (c_ptr != NULL) delete c_ptr; // NOLINT
  Py_TYPE(self)->tp_free(self);
}

static PyObject *legacy_new(PyTypeObject *type, PyObject * /*args*/, PyObject * /*kwds*/) {
  auto *self = (legacy_holder_t *)type->tp_alloc(type, 0);
  if (self != NULL) self->_c = NULL;
  return (PyObject *)self;
}

static PyTypeObject legacy_L_pytype = {PyVarObject_HEAD_INIT(NULL, 0) "legacy_reg.L", sizeof(legacy_holder_t)};

using legacy_table_t = std::shared_ptr<c2py::pto_table_t>; // what the capsule points to

static void legacy_table_destructor(PyObject *capsule) {
  delete static_cast<legacy_table_t *>(PyCapsule_GetPointer(capsule, "__main__.__cpp2py_table")); // NOLINT
}

// The table of the legacy cpp2py, created if no one has : cpp2py's get_conv_table does exactly this,
// and it must work whether the legacy module or the c2py one is imported first.
static c2py::pto_table_t *legacy_table() {
  c2py::pyref main_mod = PyImport_GetModule(c2py::pyref::string("__main__"));
  if (main_mod.is_null()) return nullptr;

  if (PyObject_HasAttrString(main_mod, "__cpp2py_table")) {
    c2py::pyref capsule = PyObject_GetAttrString(main_mod, "__cpp2py_table");
    void *ptr           = (capsule.is_null() ? nullptr : PyCapsule_GetPointer(capsule, "__main__.__cpp2py_table"));
    return (ptr == nullptr ? nullptr : static_cast<legacy_table_t *>(ptr)->get());
  }

  auto *owner         = new legacy_table_t{std::make_shared<c2py::pto_table_t>()}; // NOLINT owned by the capsule
  c2py::pyref capsule = PyCapsule_New((void *)owner, "__main__.__cpp2py_table", (PyCapsule_Destructor)legacy_table_destructor);
  if (capsule.is_null() or PyObject_SetAttrString(main_mod, "__cpp2py_table", capsule) != 0) return nullptr;
  return owner->get();
}

// Write the entry, as cpp2py does : `conv_table[typeid(T).name()] = &its_type;`, an assignment.
static bool register_the_legacy_cpp2py_way() {
  auto *table = legacy_table();
  if (table == nullptr) return false;
  (*table)[std::type_index(typeid(L)).name()] = &legacy_L_pytype;
  return true;
}

static struct PyModuleDef module_def = {PyModuleDef_HEAD_INIT, "legacy_reg", "A fake legacy cpp2py registration of L", -1, nullptr};

extern "C" __attribute__((visibility("default"))) PyObject *PyInit_legacy_reg() {

  legacy_L_pytype.tp_dealloc = legacy_dealloc;
  legacy_L_pytype.tp_flags   = Py_TPFLAGS_DEFAULT;
  legacy_L_pytype.tp_doc     = "A L, held the legacy cpp2py way";
  legacy_L_pytype.tp_new     = legacy_new;
  if (PyType_Ready(&legacy_L_pytype) < 0) return NULL;

  PyObject *m = PyModule_Create(&module_def);
  if (m == NULL) return NULL;

  if (not register_the_legacy_cpp2py_way()) {
    Py_DECREF(m);
    return NULL;
  }

  Py_INCREF(&legacy_L_pytype);
  if (PyModule_AddObject(m, "L", (PyObject *)&legacy_L_pytype) < 0) {
    Py_DECREF(&legacy_L_pytype);
    Py_DECREF(m);
    return NULL;
  }

  return m;
}
